# Production configuration template
# Secrets should be set via environment variables in DigitalOcean:
#
# Required environment variables:
#   APP_database__host
#   APP_database__username
#   APP_database__password
#   APP_database__database_name
#
# Optional (will use base.yaml defaults if not set):
#   APP_database__port (default: 5432)
#   APP_database__max_connections (default: 5)
#   APP_app__port (default: 8000)

app:
  # Bind to all interfaces in production
  host: 0.0.0.0
  # Port can be overridden via APP__app__port environment variable
